const AdaptiveLab={
 ids:['argument','probability','route','rotation'],
 level(module){return Math.max(1,Math.min(5,brainRecords(module).at(-1)?.metrics.nextLevel||1))},
 adjust(level,streak,ok){return Math.max(1,Math.min(5,level+(streak>=2?(ok?1:-1):0)))},
 choices(question,values,explanation){const options=shuffle(values.map((text,i)=>({text,correct:i===0})));return {question,options:options.map(v=>v.text),answer:options.findIndex(v=>v.correct),explanation}},
 argument(level){
 const names=shuffle(['янтарный','синий','белый','алый','зелёный','серебряный','золотой','фиолетовый']).slice(0,level<3?3:level<5?4:5),negative=rand(0,1)===1,conditional=rand(0,1)===1;
 const prop=i=>`горит ${names[i]} сигнал`,n=names.length-1;
 const rules=names.slice(1).map((_,i)=>[i,i+1,negative&&i===n-1]);
 const conditions=rules.map(([a,b,neg])=>conditional?`Если ${prop(a)}, то ${neg?'не ':''}${prop(b)}.`:`Все объекты со свойством «${names[a]}» ${neg?'не имеют':'имеют'} свойство «${names[b]}».`);
 const say=(a,b,neg)=>conditional?`Если ${prop(a)}, то ${neg?'не ':''}${prop(b)}.`:`Все объекты со свойством «${names[a]}» ${neg?'не имеют':'имеют'} свойство «${names[b]}».`;
 const claims=[[0,n,negative],[n,0,false],[0,n,!negative],[1,0,false]];
 const task=this.choices('Какой вывод обязательно следует?\n'+conditions.join('\n'),claims.map(c=>say(...c)),`Пройди цепочку условий от «${names[0]}» к «${names[n]}». Каждое следствие становится условием следующего шага. Поэтому последнее свойство ${negative?'исключено':'обязательно'}. Обратное утверждение из этих условий не следует.`);
 task.rules=rules;task.claims=claims;task.variables=names.length;return task;
 },
 probability(level){
 const type=rand(0,Math.min(5,level)),a=rand(2,9),b=rand(2,9),total=a+b;let q,v,ex;
 if(type===0){q=`В мешке ${a} красных и ${b} синих жетонов. Какова вероятность достать красный, в процентах?`;v=a/total*100;ex=`Благоприятных исходов ${a} из ${total}: ${a} ÷ ${total} × 100%.`}
 if(type===1){const price=rand(5,40)*100,p=rand(1,7)*5;q=`Цена ${price} монет. Скидка ${p}%. Сколько монет составит скидка?`;v=price*p/100;ex=`${price} × ${p} ÷ 100 = ${v}.`}
 if(type===2){q=`Два независимых события имеют вероятности ${a*10}% и ${b*10}%. Какова вероятность обоих, в процентах?`;v=a*b;ex=`Для независимых событий вероятности перемножаются: ${a/10} × ${b/10} × 100% = ${v}%.`}
 if(type===3){const other=rand(5,30);q=`В группе ${total+other} человек. Из ${total} участников кружка ${a} играют в шахматы. Выбран участник кружка. Какова вероятность, что он играет в шахматы, в процентах?`;v=a/total*100;ex=`Условие ограничивает выбор ${total} участниками кружка: ${a} ÷ ${total} × 100%. Остальные ${other} человек не учитываются.`}
 if(type===4){const p=rand(2,8)*5,r=rand(1,4)*10;q=`Исходный риск ${p}%. Мера снижает его на ${r}% относительно исходного. Каков оставшийся риск, в процентах?`;v=p*(1-r/100);ex=`Снижение относительно исходного риска: ${p} × (1 − ${r}/100) = ${v.toFixed(2)}%.`}
 if(type===5){const prize=rand(2,15)*10,cost=rand(1,8)*5;q=`С вероятностью ${a*10}% выплата составит ${prize} монет, иначе 0. Участие стоит ${cost} монет. Какова ожидаемая чистая прибыль за попытку?`;v=a/10*prize-cost;ex=`Ожидаемая выплата минус цена: ${a/10} × ${prize} − ${cost} = ${v.toFixed(2)}.`}
 const rounded=Math.round(v*100)/100,values=[rounded];while(values.length<4){const x=Math.round((rounded+rand(-12,12)*(type===1?5:1))*100)/100;if(!values.includes(x)&&(type===5||x>=0)&&(type===1||type===5||x<=100))values.push(x)}
 const fmt=x=>x.toLocaleString('ru-RU',{maximumFractionDigits:2});return {...this.choices(q+' Ответ округлён до сотых.',values.map(fmt),ex),value:rounded,type};
 },
 normalize(cells){const x=Math.min(...cells.map(c=>c[0])),y=Math.min(...cells.map(c=>c[1]));return cells.map(c=>[c[0]-x,c[1]-y]).sort((a,b)=>a[0]-b[0]||a[1]-b[1])},
 turn(cells,n=1){for(let i=0;i<n;i++)cells=cells.map(([x,y])=>[-y,x]);return this.normalize(cells)},
 signature(cells){return JSON.stringify(this.normalize(cells))},
 canonical(cells){return [0,1,2,3].map(n=>this.signature(this.turn(cells,n))).sort()[0]},
 shape(count){const cells=[[0,0]];while(cells.length<count){const [x,y]=cells[rand(0,cells.length-1)],d=[[0,1],[1,0],[0,-1],[-1,0]][rand(0,3)],p=[x+d[0],y+d[1]];if(!cells.some(c=>c[0]===p[0]&&c[1]===p[1]))cells.push(p)}return this.normalize(cells)},
 rotation(level){let cells,mirror;do{cells=this.shape(5+level);mirror=this.normalize(cells.map(([x,y])=>[-x,y]))}while(this.canonical(cells)===this.canonical(mirror));const turns=rand(1,3),correct=this.turn(cells,turns),shapes=[correct,mirror],keys=new Set([this.canonical(cells),this.canonical(mirror)]);while(shapes.length<4){const shape=this.shape(cells.length),key=this.canonical(shape);if(!keys.has(key)){keys.add(key);shapes.push(shape)}}const options=shuffle(shapes.map((shape,i)=>({shape,correct:i===0})));return {question:'Какая фигура совпадёт с исходной после поворота? Отражать фигуру нельзя.',cells,turns,shapes:options.map(o=>o.shape),options:['А','Б','В','Г'],answer:options.findIndex(o=>o.correct),explanation:`Правильная фигура получается поворотом на ${turns*90}°. При вращении взаимное расположение клеток сохраняется; зеркальное отражение его меняет.`}},
 svg(cells,animate=0){return `<svg viewBox="-11 -11 22 22" role="img" aria-label="Фигура из ${cells.length} клеток" style="width:100%;max-width:180px;height:140px"><g>${animate?`<animateTransform attributeName="transform" type="rotate" from="0" to="${animate*90}" dur="1.5s" fill="freeze"/>`:''}${cells.map(([x,y])=>`<rect x="${(x-(Math.max(...cells.map(c=>c[0]))+1)/2)*2}" y="${(y-(Math.max(...cells.map(c=>c[1]))+1)/2)*2}" width="1.85" height="1.85" rx=".18" fill="currentColor"/>`).join('')}</g></svg>`},
 solve(map){const {size,walls,points,key,door,goal}=map,full=(1<<points.length)-1,queue=[{pos:0,mask:0,key:false,path:[]}],seen=new Set(['0:0:false']);for(let i=0;i<queue.length;i++){const s=queue[i];if(s.pos===goal&&s.mask===full&&(key<0||s.key))return s.path;for(const d of [-size,size,-1,1]){const p=s.pos+d;if(p<0||p>=size*size||Math.abs(p%size-s.pos%size)+Math.abs(Math.floor(p/size)-Math.floor(s.pos/size))!==1||walls.includes(p)||p===door&&!s.key)continue;const got=s.key||p===key,mask=s.mask|(points.includes(p)?1<<points.indexOf(p):0),id=`${p}:${mask}:${got}`;if(!seen.has(id)){seen.add(id);queue.push({pos:p,mask,key:got,path:[...s.path,p]})}}}return null},
 route(level){const size=level<3?5:6,goal=size*size-1;for(let attempt=0;attempt<100;attempt++){const free=shuffle(Array.from({length:size*size-2},(_,i)=>i+1)),points=free.splice(0,level>=2?Math.min(2,level-1):0),key=level>=3?free.pop():-1,door=level>=3?free.pop():-1,walls=free.slice(0,3+level),map={size,goal,points,key,door,walls},path=this.solve(map);if(path){map.path=path;map.limit=level>=4?path.length+(level===5?0:3):null;return map}}const map={size,goal,points:[],key:-1,door:-1,walls:[]};map.path=this.solve(map);map.limit=level>=4?map.path.length:null;return map},
 intro(module){$('#game-body').innerHTML=`<div class="game-panel"><h3 class="game-title">${esc(MODULES.find(m=>m[0]===module)[1])}</h3><p class="muted">${module==='route'?'6 карт. Двигайся по соседним клеткам вверх, вниз, влево или вправо. Собери все точки и ключ перед дверью. Цель — самый короткий путь.':'10 заданий. После каждого ответа — объяснение.'}</p><p class="muted">Два верных ответа подряд повышают сложность, две ошибки — понижают. В маршруте верным считается оптимальный путь. Уровень сохраняется между сессиями.</p><p class="field-hint">Баллы: точность — до 94, сложность — до 5, скорость — до 1. Новые задания без лимита повторов.</p><button class="btn primary" id="adaptive-start">Начать · уровень ${this.level(module)}</button></div>`;$('#adaptive-start').onclick=()=>this.start(module)},
 start(module){const session=BrainLab.session,active=()=>BrainLab.session===session&&!session.saved;session.start=performance.now();let level=this.level(module),peak=level,index=0,correct=0,streak=0,last=null;const rounds=module==='route'?6:10,times=[],levels=[];
 const next=()=>{if(!active())return;const current=level;let done=false;levels.push(current);const started=performance.now();$('#game-body').innerHTML=`<div class="flex between wrap small muted"><span>Задание ${index+1} из ${rounds}</span><span>Уровень ${level}/5 · Верно ${correct}</span></div><div id="adaptive-task" class="space"></div><div id="adaptive-feedback" class="space" aria-live="polite"></div>`;
 const finish=(ok,ex)=>{if(done||!active())return;done=true;times.push(Math.max(0,performance.now()-started));index++;if(ok)correct++;streak=last===ok?streak+1:1;last=ok;if(streak>=2){level=this.adjust(level,streak,ok);streak=0}peak=Math.max(peak,level);$('#adaptive-feedback').innerHTML=`<div class="explanation"><strong class="${ok?'accent':'gold'}">${ok?'Верно':'Разберём решение'}</strong><div class="space">${ex}</div></div><button class="btn primary space" id="adaptive-next">${index===rounds?'Посмотреть результат':'Следующее задание'}</button>`;let advanced=false;$('#adaptive-next').onclick=()=>{if(advanced||!active())return;advanced=true;if(index<rounds)return next();const accuracy=Math.round(correct/rounds*100),averageTime=Math.round(times.reduce((a,b)=>a+b,0)/rounds),difficulty=levels.reduce((a,b)=>a+b,0)/rounds,score=correct?Math.min(100,Math.floor(accuracy*.94+(difficulty-1)/4*5+Math.max(0,1-averageTime/(module==='route'?120000:60000))*1)):0;BrainLab.result('Тренировка завершена',`<div class="game-metrics wide"><div><strong>${score}/100</strong>Баллы</div><div><strong>${accuracy}%</strong>Точность</div><div><strong>${peak}/5</strong>Достигнутый уровень</div><div><strong>${(averageTime/1000).toFixed(1)}</strong>Среднее, с</div></div><p class="muted">Следующая сессия начнётся с уровня ${level}. ${module==='route'?'Точность — доля карт, пройденных оптимально.':''}</p>`,module,{accuracy,averageTime,difficulty,level:peak,nextLevel:level,rounds},score,correct>0)}};
 if(module==='route'){const map=this.route(level);let pos=0,path=[],visited=new Set(),hasKey=false;const paint=()=>{const labels=p=>p===pos?'●':map.walls.includes(p)?'■':p===map.door&&!hasKey?'▣':p===map.key&&!hasKey?'⚿':map.points.includes(p)&&!visited.has(p)?'◆':p===map.goal?'◎':'·';$('#adaptive-task').innerHTML=`<p class="small muted">● Ты · ◎ Цель · ◆ Точки · ⚿ Ключ · ▣ Дверь · ■ Стена</p><p>Ходов: ${path.length}${map.limit!==null?' / лимит '+map.limit:''} · Точек: ${visited.size}/${map.points.length}</p><div class="game-grid" style="grid-template-columns:repeat(${map.size},1fr);max-width:440px;margin:auto">${Array.from({length:map.size*map.size},(_,p)=>`<button class="game-cell" data-route-cell="${p}" aria-label="Клетка ${Math.floor(p/map.size)+1}, ${p%map.size+1}: ${labels(p)}" ${done||map.walls.includes(p)?'disabled':''}>${labels(p)}</button>`).join('')}</div><button class="btn space" id="route-giveup">Показать решение</button>`;$$('[data-route-cell]').forEach(b=>b.onclick=()=>{if(done||!active())return;const p=+b.dataset.routeCell;if(Math.abs(p%map.size-pos%map.size)+Math.abs(Math.floor(p/map.size)-Math.floor(pos/map.size))!==1)return;if(p===map.door&&!hasKey)return;pos=p;path.push(p);if(p===map.key)hasKey=true;if(map.points.includes(p))visited.add(p);const win=p===map.goal&&visited.size===map.points.length&&(map.key<0||hasKey);if(win||map.limit!==null&&path.length>=map.limit){end(win&&path.length===map.path.length);return}paint()});$('#route-giveup').onclick=()=>end(false)};
 const end=ok=>{if(done||!active())return;finish(ok,`<p>Твой путь: ${path.length} ходов / оптимальный: ${map.path.length}.</p><p class="small muted">Один из оптимальных маршрутов (строка, столбец): ${[0,...map.path].map(p=>`(${Math.floor(p/map.size)+1}, ${p%map.size+1})`).join(' → ')}</p>`);paint();$('#route-giveup').disabled=true};paint();return}
 const task=this[module](level);$('#adaptive-task').innerHTML=`${module==='rotation'?`<div class="flex wrap"><div style="flex:1;min-width:160px"><p class="muted">Исходная фигура</p>${this.svg(task.cells)}</div><div style="flex:2;min-width:230px"><p>${esc(task.question)}</p><div class="compare-choices" style="display:grid;grid-template-columns:repeat(2,1fr)">${task.options.map((o,i)=>`<button class="btn" style="display:block" data-adaptive-choice="${i}">${this.svg(task.shapes[i])}<span>Вариант ${o}</span></button>`).join('')}</div></div></div>`:`<p class="game-question" style="white-space:pre-line">${esc(task.question)}</p><div class="answer-list space">${task.options.map((o,i)=>`<button class="answer" data-adaptive-choice="${i}">${esc(o)}</button>`).join('')}</div>`}`;$$('[data-adaptive-choice]').forEach(b=>b.onclick=()=>{if(done||!active())return;const ok=+b.dataset.adaptiveChoice===task.answer;$$('[data-adaptive-choice]').forEach(x=>{x.disabled=true;if(+x.dataset.adaptiveChoice===task.answer)x.classList.add('correct')});if(!ok)b.classList.add('wrong');finish(ok,`<p>${esc(task.explanation)}</p>${module==='rotation'&&!ok?`<p>Поворот исходной фигуры к правильному варианту:</p>${this.svg(task.cells,task.turns)}`:''}`)})};next()
 }
};

