const BRAIN_CATEGORIES=[
 {id:'logic',name:'Логика',modules:['logic','math','detective','argument']},
 {id:'memory',name:'Память',modules:['memory-sequence','memory-grid','memory-number']},
 {id:'attention',name:'Внимание',modules:['focus','schulte','oddity']},
 {id:'speed',name:'Скорость обработки',modules:['reaction','schulte','comparison','math']},
 {id:'probability',name:'Вероятностное мышление',modules:['probability']},
 {id:'argument',name:'Аргументация',modules:['argument']},
 {id:'spatial',name:'Пространственное мышление',modules:['rotation']},
 {id:'observation',name:'Наблюдательность',modules:['oddity','detective']},
 {id:'social',name:'Социальный анализ',modules:['social','emotional']},
 {id:'planning',name:'Планирование',modules:['route']},
 {id:'invention',name:'Изобретательность',modules:[]}
];
const BrainProfile={
 prefs(){return state.settings.brainProfile},
 from(){const p=this.prefs().period;return p==='all'?'2000-01-01':addDays(today(),1-Number(p))},
 rows(){const from=this.from();return BRAIN_CATEGORIES.map(c=>{const records=state.brain.sessions.filter(s=>c.modules.includes(s.module)&&s.date>=from&&s.date<=today()).sort((a,b)=>a.time.localeCompare(b.time)),mean=xs=>xs.length?Math.round(xs.reduce((n,s)=>n+s.score,0)/xs.length):null,latest=records.slice(-10),previous=records.slice(-20,-10),value=mean(latest),old=mean(previous),trend=old===null?null:value-old;return {...c,count:records.length,value,trend,records}})},
 chart(row){if(!row.records.length)return '<p class="muted small space">Для этого периода пока нет результатов.</p>';const earliest=this.prefs().period==='all'?row.records[0].date:this.from(),span=Growth.days(earliest,today()),bins=Math.min(30,span),groups=Array.from({length:bins},()=>[]);for(const r of row.records){const i=Math.min(bins-1,Math.floor((Growth.days(earliest,r.date)-1)/span*bins));groups[i].push(r)}const points=groups.flatMap((records,i)=>records.length?[{x:45+(bins===1?.5:i/(bins-1))*480,y:155-records.reduce((n,s)=>n+s.score,0)/records.length*1.3,date:records[0].date,score:Math.round(records.reduce((n,s)=>n+s.score,0)/records.length),count:records.length}]:[]);return `<svg class="chart" viewBox="0 0 560 190" role="img" aria-label="${esc(row.name)}: ${points.map(p=>`${p.date} — ${p.score} баллов`).join(', ')}">${[0,25,50,75,100].map(n=>`<line x1="40" x2="530" y1="${155-n*1.3}" y2="${155-n*1.3}" stroke="#2a3639" stroke-dasharray="3 5"/><text x="4" y="${159-n*1.3}">${n}</text>`).join('')}<polyline points="${points.map(p=>p.x+','+p.y).join(' ')}" fill="none" stroke="var(--accent)" stroke-width="2"/>${points.map(p=>`<circle cx="${p.x}" cy="${p.y}" r="4" fill="var(--accent)"><title>${fmtDate(p.date,true)} · ${p.score}/100 · ${p.count} тренировок</title></circle>`).join('')}<text x="45" y="180">${fmtDate(earliest,true)}</text><text x="525" y="180" text-anchor="end">${fmtDate(today(),true)}</text></svg>`},
 render(compact=false){const rows=this.rows(),p=this.prefs(),chosen=rows.find(r=>r.id===p.category);return `${compact?'<section class="panel pad space"><div class="flex between wrap"><h2>Профиль способностей</h2><a class="btn ghost" href="#/brain-profile">Открыть профиль</a></div>':intro('Профиль способностей','Отдельная динамика каждого направления практики.')}<div class="toolbar space"><label class="field">Период<select data-brain-profile="period">${[['7','7 дней'],['30','30 дней'],['90','90 дней'],['all','Всё время']].map(([v,t])=>`<option value="${v}" ${p.period===v?'selected':''}>${t}</option>`).join('')}</select></label><label class="field">Направление графика<select data-brain-profile="category">${rows.map(r=>`<option value="${r.id}" ${p.category===r.id?'selected':''}>${r.name}</option>`).join('')}</select></label></div><div class="${compact?'':'panel pad'}"><h3>${esc(chosen.name)}</h3>${this.chart(chosen)}<p class="field-hint">Точки — средний балл тренировок внутри интервала. Пропуски означают отсутствие занятий.</p></div>${compact?'':`<div class="cards space">${rows.map((r,i)=>`<section class="panel pad"><div class="flex between"><h3>${r.name}</h3><span class="accent">${r.value===null?'—':r.value+' / 100'}${r.trend===null?'':r.trend>2?' ↑':r.trend< -2?' ↓':' →'}</span></div>${r.value!==null?`<div class="bar space" style="--c:${ACCENTS[i%6]};--p:${r.value}%"><i></i></div>`:''}<p class="small muted space">${r.count?`${r.count} тренировок · среднее последних ${Math.min(10,r.count)}`:r.modules.length?'Пока нет тренировок в выбранном периоде.':'Отдельная тренировка для этой категории пока отсутствует.'}</p>${r.modules.length?`<p class="field-hint">${[...new Set(r.modules.map(id=>MODULES.find(m=>m[0]===(id.startsWith('memory')?'memory':id))?.[1]))].map(esc).join(' · ')}</p>`:''}</section>`).join('')}</div>`}<p class="field-hint space">Это результаты упражнений, а не оценка интеллекта. Направления могут пересекаться. Стрелка сравнивает последние 10 занятий с предыдущими 10; сложность и состав упражнений тоже влияют на балл.</p>${compact?'</section>':''}`}
};
