const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const dummy={innerHTML:'',textContent:'',style:{},classList:{add(){},remove(){},toggle(){}},focus(){},append(){},remove(){},querySelector(){return dummy},querySelectorAll(){return []},addEventListener(){}};
const sandbox={console,structuredClone,Blob,URL,Date,Math,JSON,Number,String,Object,Array,Set,Map,Error,performance,crypto:require('crypto').webcrypto,setTimeout:()=>0,clearTimeout(){},document:{querySelector:()=>dummy,querySelectorAll:()=>[],createElement:()=>({...dummy}),addEventListener(){},body:{style:{},classList:{toggle(){}},dataset:{}}},window:{addEventListener(){},scrollTo(){}},location:{hash:'#/overview'},localStorage:{getItem:()=>null,setItem(){}},navigator:{}};
vm.createContext(sandbox);const source=fs.readFileSync('outputs/index.html','utf8').split('<script>')[1].split('</script>')[0].replace(/\ninit\(\);\s*$/,'');vm.runInContext(source,sandbox);let checks=0;
function test(name,script){const result=vm.runInContext(script,sandbox);assert.equal(result,true,name);checks++;console.log('ПРОЙДЕНО:',name)}
vm.runInContext('state=freshState(); Modal.open=()=>{};Modal.close=()=>{}; render=()=>{};save=()=>{};toast=()=>{};beep=()=>{}',sandbox);

const oldSandbox={...sandbox};vm.createContext(oldSandbox);const oldScript=fs.readFileSync('work/pre-growth.html','utf8').split('<script>')[1].split('</script>')[0].replace(/\ninit\(\);\s*$/,'');vm.runInContext(oldScript,oldSandbox);
const legacy=vm.runInContext('state=freshState();state.profile.onboarded=true;const a=state.attributes[0];state.completions=[{id:uid(),missionId:uid(),date:today(),time:new Date().toISOString(),title:"Старая миссия",duration:20,difficulty:2,xp:120,allocations:[{id:a.id,xp:120}]}];recalcAttributes();structuredClone(state)',oldSandbox);sandbox.legacy=legacy;
test('Старая копия получает новые разделы без потери опыта','(()=>{state=validateStateStrict(legacy);recalcAttributes();return totalXP()===120&&state.attributes[0].level===2&&state.attributes[0].totalXP===120&&state.phases.length===0&&state.habits.length===0&&state.persona.rules.length===0&&state.codex.length===0&&state.settings.brainProfile.period==="30"})()');
vm.runInContext(`state=freshState();const base=addDays(today(),-6);const phase={id:uid(),name:'Фундамент',description:'Ритм',startDate:base,endDate:addDays(base,29),completedAt:null,goals:['Практиковать каждый день'],missionIds:[]};state.phases.push(phase);const h={id:uid(),name:'Чтение',description:'Небольшой шаг',startDate:base,phaseId:phase.id,active:true,deleted:false,weekdays:[0,1,2,3,4,5,6],allocations:[{id:state.attributes[0].id,weight:50},{id:state.attributes[1].id,weight:50}],tiers:[{label:'5 минут',xp:5,duration:5},{label:'20 минут',xp:10,duration:20},{label:'45 минут',xp:15,duration:45}],schedule:[{from:base,phaseId:phase.id,active:true,weekdays:[0,1,2,3,4,5,6]}]};state.habits.push(h);`,sandbox);
test('Фаза: день 7 из 30, активная и будущая','Growth.phaseDay(phase).day===7&&Growth.phaseDay(phase).total===30&&Growth.status(phase)==="active"&&Growth.status({...phase,startDate:addDays(today(),1)})==="future"');
test('Минимум засчитывает день и распределяет опыт точно','(()=>{Growth.mark(h.id,today(),0);return state.habitCompletions.length===1&&totalXP()===5&&state.habitCompletions[0].allocations.reduce((n,x)=>n+x.xp,0)===5&&Growth.habitStats(h).current===1})()');
test('Повторный клик не дублирует, повышение заменяет награду','(()=>{Growth.mark(h.id,today(),0);Growth.mark(h.id,today(),2);return state.habitCompletions.length===1&&totalXP()===15&&state.activity.filter(a=>a.type==="habit").length===1})()');
test('Будущие дни и чужая фаза не начисляют опыт','(()=>{Growth.mark(h.id,addDays(today(),1),2);const prior=totalXP();const end=phase.endDate;phase.endDate=addDays(today(),-1);Growth.mark(h.id,today(),1);phase.endDate=end;return prior===totalXP()})()');
test('Семь минимумов дают семь успешных дней фазы','(()=>{Growth.undo(h.id,today());for(let i=0;i<7;i++)Growth.mark(h.id,addDays(base,i),0);const r=Growth.report(phase);return totalXP()===35&&Growth.habitStats(h).current===7&&Growth.habitStats(h).best===7&&r.days===7&&r.scheduled===7&&r.done===7&&r.compliance===100&&r.xp===35&&r.attrs.reduce((n,a)=>n+a.xp,0)===35})()');
test('Пауза и архив не переписывают прошлое','(()=>{Growth.schedule(h,false);h.deleted=true;const r=Growth.report(phase);return r.scheduled===7&&r.compliance===100&&totalXP()===35&&!Growth.due(h,addDays(today(),1))&&Growth.due(h,addDays(today(),-1))})()');
test('Отмена корректно возвращает опыт и серию','(()=>{Growth.undo(h.id,addDays(today(),-2));return totalXP()===30&&Growth.habitStats(h).current===2&&Growth.habitStats(h).best===4})()');
test('Завершённая фаза отключает будущие дни','(()=>{phase.completedAt=today();Growth.schedule(h,true);h.deleted=false;return Growth.status(phase)==="completed"&&!Growth.due(h,addDays(today(),1))})()');
test('Дни недели сохраняют серию через выходные','(()=>{const weekend={...h,schedule:[{...h.schedule[0],weekdays:[1,2,3,4,5]}]};return !Growth.due(weekend,"2026-10-03")&&!Growth.due(weekend,"2026-10-04")})()');
test('Старая миссия учитывается вместе с привычками','(()=>{state.completions=legacy.completions.map(c=>({...c,id:uid(),allocations:[{id:state.attributes[0].id,xp:c.xp}]}));recalcAttributes();return totalXP()===150&&periodXP(base)===150&&developmentData().all.reduce((n,r)=>n+r.value,0)===150})()');
vm.runInContext(`state.persona={...state.persona,name:'Наблюдатель',traits:['Выдержка'],antiTraits:['Импульсивность'],habitIds:[h.id],rules:[{id:uid(),situation:'Конфликт',oldReaction:'Отвечаю сразу',newReaction:'Сначала уточняю факты'}],references:[{id:uid(),name:'Образ',source:'Личная заметка',take:'Спокойная речь',avoid:'Давление',notes:''}]};state.codex=[{id:uid(),title:'Книга',category:'Книги',status:'active',tags:['анализ'],rating:8,attitude:'Полезна',notes:'Заметка',addedAt:today(),missionId:null,details:{author:'Автор',progress:'20 / 100',ideas:'Одна идея'}}];`,sandbox);
test('Полный экспорт восстанавливает все пять модулей','(()=>{const v=validateStateStrict(JSON.parse(BackupManager.serialize()).data);return v.phases.length===1&&v.habits[0].schedule.length===2&&v.habitCompletions.length===6&&v.persona.rules.length===1&&v.persona.references.length===1&&v.codex[0].details.progress==="20 / 100"&&v.codex[0].tags[0]==="анализ"})()');
for(const [label,mutation]of [['отрицательный опыт','s.habitCompletions[0].xp=-1'],['повтор отметки','s.habitCompletions.push({...s.habitCompletions[0],id:uid()})'],['неверные даты','s.phases[0].endDate=addDays(s.phases[0].startDate,-1)'],['повреждённая сущность','s.codex=null'],['неверный профиль','s.settings.brainProfile.category="unknown"']])test('Импорт отклоняет: '+label,`(()=>{const s=structuredClone(state);${mutation};try{validateStateStrict(s);return false}catch{return true}})()`);
test('Профиль способностей различает категории и отсутствие данных','(()=>{const s={id:uid(),module:"social",date:today(),time:new Date().toISOString(),score:78,metrics:{},correct:true,xp:0,duration:1,title:"Радар",allocations:[]};state.brain.sessions=[s,{...s,id:uid(),module:"memory-number",score:50}];const rows=BrainProfile.rows();return rows.find(r=>r.id==="social").value===78&&rows.find(r=>r.id==="memory").value===50&&rows.find(r=>r.id==="logic").value===null})()');
test('Периоды 7/30/90/всё время фильтруют историю','(()=>{const s=state.brain.sessions[0];state.brain.sessions.push({...s,id:uid(),date:addDays(today(),-45),time:parseDate(addDays(today(),-45)).toISOString(),score:20});state.settings.brainProfile.period="30";const n=BrainProfile.rows().find(r=>r.id==="social").count;state.settings.brainProfile.period="90";return n===1&&BrainProfile.rows().find(r=>r.id==="social").count===2})()');
test('Новые экраны выводятся без ошибок и экранируют текст','(()=>{state.persona.name="<img onerror=alert(1)>";return [GrowthUI.phases(),GrowthUI.habits(),GrowthUI.persona(),GrowthUI.codex(),BrainProfile.render(),renderToday(),renderDashboard(),renderStatistics()].every(html=>html.length>100&&!html.includes("NaN")&&!html.includes("<img onerror"))})()');
console.log('Итого:',checks,'проверок новых функций пройдено.');
