// Monthly growth uses the existing local snapshot, rewards and journal.
const HABIT_TIERS=[['minimum','Минимум'],['standard','Стандарт'],['extended','Расширенно']];
const CODEX_CATEGORIES=['Книги','Фильмы','Сериалы','Музыка','Персонажи','Люди','Идеи','Концепции','Цитаты','Темы для изучения','Навыки'];
const CODEX_FIELDS={
 'Книги':[['author','Автор'],['progress','Прогресс, своими словами'],['studying','Что изучаю'],['ideas','Основные идеи'],['take','Что беру себе'],['quotes','Цитаты']],
 'Фильмы':[['genre','Жанр'],['characters','Персонажи'],['liked','Что понравилось'],['atmosphere','Атмосфера'],['behavior','Поведение персонажей'],['take','Что перенять']],
 'Сериалы':[['genre','Жанр'],['characters','Персонажи'],['liked','Что понравилось'],['atmosphere','Атмосфера'],['behavior','Поведение персонажей'],['take','Что перенять']],
 'Музыка':[['artist','Исполнитель'],['release','Альбом / трек'],['mood','Настроение'],['style','Стиль'],['when','Когда слушать']],
 'Персонажи':[['source','Произведение'],['traits','Черты'],['speech','Манера речи'],['style','Стиль'],['behavior','Поведение'],['take','Что перенять'],['avoid','Что не перенимать']],
 'Люди':[['source','Источник'],['traits','Черты'],['take','Что перенять'],['avoid','Что не перенимать']],
 'Идеи':[['definition','Описание своими словами'],['area','Область'],['related','Связанные идеи'],['application','Пример применения']],
 'Концепции':[['definition','Описание своими словами'],['area','Область'],['related','Связанные идеи'],['application','Пример применения']],
 'Цитаты':[['quote','Текст цитаты'],['source','Автор / источник']],
 'Темы для изучения':[['area','Область'],['interest','Уровень интереса'],['materials','Связанные материалы']],
 'Навыки':[['area','Область'],['progress','Текущий уровень'],['materials','Материалы'],['application','Где применять']]
};
function growthDefaults(){return {growthVersion:1,phases:[],habits:[],habitCompletions:[],persona:{name:'',description:'',philosophy:'',traits:[],antiTraits:[],communication:'',appearance:'',values:[],notes:'',habitIds:[],rules:[],references:[]},codex:[]}}
function developmentRecords(){return [...state.completions,...state.brain.sessions,...state.habitCompletions]}
const Growth={
 days(from,to){return Math.max(0,Math.round((parseDate(to)-parseDate(from))/86400000)+1)},
 status(p,date=today()){return p.completedAt||date>p.endDate?'completed':date<p.startDate?'future':'active'},
 end(p){return p.completedAt&&p.completedAt<p.endDate?p.completedAt:p.endDate},
 current(){return state.phases.filter(p=>this.status(p)==='active').sort((a,b)=>b.startDate.localeCompare(a.startDate))[0]},
 phaseDay(p,date=today()){const total=this.days(p.startDate,p.endDate),day=Math.min(total,Math.max(0,this.days(p.startDate,date))),elapsed=p.completedAt?Math.min(total,this.days(p.startDate,p.completedAt)):day;return {total,day:elapsed,percent:Math.round(elapsed/total*100)}},
 plan(h,date){return h.schedule.filter(s=>s.from<=date).at(-1)},
 due(h,date){const s=this.plan(h,date);if(!s||!s.active||!s.weekdays.includes(parseDate(date).getDay()))return false;const p=state.phases.find(p=>p.id===s.phaseId);return !p||date>=p.startDate&&date<=this.end(p)},
 done(id,date){return state.habitCompletions.find(c=>c.habitId===id&&c.date===date)},
 on(date){return state.habits.filter(h=>!h.deleted&&this.due(h,date)||this.done(h.id,date))},
 habitStats(h){const dates=new Set(state.habitCompletions.filter(c=>c.habitId===h.id).map(c=>c.date));let run=0,best=0,current=0,lastDue=null;for(let d=h.startDate;d<=today();d=addDays(d,1)){if(!this.due(h,d))continue;if(d===today()&&!dates.has(d))continue;run=dates.has(d)?run+1:0;best=Math.max(best,run);current=run;lastDue=d}return {current,best,done:dates.size,lastDue}},
 commit(message){recalcAttributes();save();render();if(message)toast(message)},
 mark(id,date,tier){const h=state.habits.find(h=>h.id===id);if(!h||h.deleted||date>today()||!this.due(h,date)||!HABIT_TIERS[tier])return;const prior=this.done(id,date);if(prior?.tier===tier)return;const xp=Math.min(10000,Math.round(h.tiers[tier].xp*state.settings.xpMultiplier)),allocations=XPSystem.distribute(xp,h.allocations);if(!allocations.length)return toast('Добавь существующий атрибут в привычку.',true);const oldLevel=XPSystem.level(totalXP()).level,s=this.plan(h,date),c={id:prior?.id||uid(),habitId:id,phaseId:s.phaseId,title:h.name,date,time:new Date().toISOString(),tier,xp,duration:h.tiers[tier].duration,allocations};state.habitCompletions=state.habitCompletions.filter(x=>x!==prior);state.habitCompletions.push(c);if(prior)state.activity=state.activity.filter(x=>x.completionId!==prior.id);addActivity(`${h.name} · ${HABIT_TIERS[tier][1]}`,'habit',xp,{completionId:c.id});recalcAttributes();if(XPSystem.level(totalXP()).level>oldLevel){addActivity(rankFor()+' — уровень '+XPSystem.level(totalXP()).level,'level');toast(rankFor()+' · Уровень '+XPSystem.level(totalXP()).level)}Achievements.reconcile();Achievements.check();save();render();toast(prior?'Уровень выполнения обновлён':'Привычка выполнена');beep()},
 undo(id,date){const c=this.done(id,date);if(!c)return;state.habitCompletions=state.habitCompletions.filter(x=>x!==c);state.activity=state.activity.filter(x=>x.completionId!==c.id);recalcAttributes();Achievements.reconcile();save();render();toast('Выполнение привычки отменено')},
 schedule(h,active){const change=this.done(h.id,today())?addDays(today(),1):today(),from=change<h.startDate?h.startDate:change,old=this.plan(h,from)||h.schedule.at(-1);h.active=active;const entry={...structuredClone(old),from,active,phaseId:h.phaseId,weekdays:[...h.weekdays]};h.schedule=h.schedule.filter(s=>s.from!==from);h.schedule.push(entry);h.schedule.sort((a,b)=>a.from.localeCompare(b.from))},
 report(p){const end=this.end(p)<today()?this.end(p):today(),habits=state.habits.filter(h=>h.schedule.some(s=>s.phaseId===p.id));let scheduled=0,done=0;const activeDays=new Set();for(let d=p.startDate;d<=end;d=addDays(d,1)){for(const h of habits){const plan=this.plan(h,d);if(plan?.phaseId===p.id&&this.due(h,d)){scheduled++;if(this.done(h.id,d)){done++;activeDays.add(d)}}}}const missions=state.completions.filter(c=>c.date>=p.startDate&&c.date<=end&&(!p.missionIds.length||p.missionIds.includes(c.missionId))),records=developmentRecords().filter(c=>c.date>=p.startDate&&c.date<=end&&(c.habitId?c.phaseId===p.id:c.missionId?!p.missionIds.length||p.missionIds.includes(c.missionId):true));records.forEach(r=>activeDays.add(r.date));const attrs=state.attributes.map(a=>{const before=developmentRecords().filter(c=>c.date<p.startDate).flatMap(c=>c.allocations).filter(x=>x.id===a.id).reduce((n,x)=>n+x.xp,0),xp=records.flatMap(c=>c.allocations).filter(x=>x.id===a.id).reduce((n,x)=>n+x.xp,0);return {name:a.name,xp,before:XPSystem.level(before).level,after:XPSystem.level(before+xp).level}}).filter(a=>a.xp>0);return {days:activeDays.size,scheduled,done,compliance:scheduled?Math.round(done/scheduled*100):null,missions:missions.length,xp:records.reduce((n,r)=>n+r.xp,0),duration:records.reduce((n,r)=>n+r.duration,0),attrs}},
 validate(raw,out){
 const fail=msg=>{throw Error(msg||'Некорректные данные новых разделов.')},obj=v=>v&&typeof v==='object'&&!Array.isArray(v),list=(v,max=50000)=>Array.isArray(v)&&v.length<=max?v:fail(),text=(v,max=3000)=>typeof v==='string'&&v.length<=max?v:fail('Некорректное текстовое поле.'),id=v=>typeof v==='string'&&/^[a-zA-Z0-9_-]{1,100}$/.test(v)?v:fail('Некорректный идентификатор.'),optional=v=>v===null?null:id(v),num=(v,max=10000)=>Number.isFinite(v)&&v>=0&&v<=max?v:fail('Некорректное число.'),date=v=>validDate(v)?v:fail('Некорректная дата.'),bool=v=>typeof v==='boolean'?v:fail(),unique=items=>new Set(items.map(x=>x.id)).size===items.length?items:fail('Повтор идентификатора.'),words=v=>list(v,100).map(x=>text(x,300)),days=v=>{const xs=list(v,7).map(x=>num(x,6));if(!xs.length||xs.some(x=>!Number.isInteger(x))||new Set(xs).size!==xs.length)fail('Выбери дни недели.');return xs},iso=v=>typeof v==='string'&&v.length<50&&!isNaN(Date.parse(v))?v:fail(),defaults=growthDefaults();
 if(raw.growthVersion!==undefined&&raw.growthVersion!==1)fail('Версия новых разделов не поддерживается.');
 out.growthVersion=1;out.phases=unique(list((raw.phases===undefined?defaults.phases:raw.phases),1000).map(p=>{const startDate=date(p.startDate),endDate=date(p.endDate);if(endDate<startDate||this.days(startDate,endDate)>3660)fail('Фаза: проверь период.');const completedAt=p.completedAt===null?null:date(p.completedAt);if(completedAt&&(completedAt<startDate||completedAt>endDate))fail('Фаза: некорректное завершение.');return {id:id(p.id),name:text(p.name,100),description:text(p.description),startDate,endDate,completedAt,goals:words(p.goals),missionIds:list(p.missionIds,1000).map(id)}}));
 const weights=v=>{const rows=list(v,1000).map(x=>({id:id(x.id),weight:num(x.weight,100)}));if(rows.length&&(new Set(rows.map(x=>x.id)).size!==rows.length||Math.abs(rows.reduce((n,x)=>n+x.weight,0)-100)>.00001))fail('Доли привычки должны давать 100%.');return rows};
 out.habits=unique(list((raw.habits===undefined?defaults.habits:raw.habits),10000).map(h=>{const tiers=list(h.tiers,3).map(t=>({label:text(t.label,300),xp:num(t.xp,1000),duration:num(t.duration,1440)}));if(tiers.length!==3||tiers.some(t=>!Number.isInteger(t.xp)||!t.label.trim())||tiers[0].xp>tiers[1].xp||tiers[1].xp>tiers[2].xp)fail('Нужно три уровня привычки.');const schedule=list(h.schedule,10000).map(s=>({from:date(s.from),active:bool(s.active),phaseId:optional(s.phaseId),weekdays:days(s.weekdays)})).sort((a,b)=>a.from.localeCompare(b.from));if(!schedule.length||new Set(schedule.map(s=>s.from)).size!==schedule.length)fail('Некорректная история расписания.');const startDate=date(h.startDate);if(schedule[0].from!==startDate)fail('Некорректное начало привычки.');return {id:id(h.id),name:text(h.name,160),description:text(h.description),active:bool(h.active),deleted:bool(h.deleted),weekdays:days(h.weekdays),startDate,phaseId:optional(h.phaseId),allocations:weights(h.allocations),tiers,schedule}}));
 out.habitCompletions=unique(list((raw.habitCompletions===undefined?defaults.habitCompletions:raw.habitCompletions),200000).map(c=>{const xp=num(c.xp),allocations=list(c.allocations,1000).map(x=>({id:id(x.id),xp:num(x.xp)}));if(!Number.isInteger(xp)||allocations.some(x=>!Number.isInteger(x.xp))||new Set(allocations.map(x=>x.id)).size!==allocations.length||allocations.reduce((n,x)=>n+x.xp,0)!==xp)fail('Награда привычки не совпадает с распределением.');const tier=num(c.tier,2);if(!Number.isInteger(tier))fail();return {id:id(c.id),habitId:id(c.habitId),phaseId:optional(c.phaseId),date:date(c.date),time:iso(c.time),title:text(c.title,300),tier,xp,duration:num(c.duration,1440),allocations}}));if(new Set(out.habitCompletions.map(c=>c.habitId+'|'+c.date)).size!==out.habitCompletions.length)fail('Повтор привычки за один день.');
 const p=raw.persona===undefined?defaults.persona:raw.persona;if(!obj(p))fail();out.persona={};for(const key of ['name','description','philosophy','communication','appearance','notes'])out.persona[key]=text(p[key],key==='name'?100:3000);for(const key of ['traits','antiTraits','values'])out.persona[key]=words(p[key]);out.persona.habitIds=list(p.habitIds,1000).map(id);out.persona.rules=unique(list(p.rules,1000).map(r=>({id:id(r.id),situation:text(r.situation,1000),oldReaction:text(r.oldReaction,1000),newReaction:text(r.newReaction,1000)})));out.persona.references=unique(list(p.references,1000).map(r=>({id:id(r.id),name:text(r.name,160),source:text(r.source,300),take:text(r.take,2000),avoid:text(r.avoid,2000),notes:text(r.notes,2000)})));
 const fieldNames=new Set(Object.values(CODEX_FIELDS).flat().map(x=>x[0]));out.codex=unique(list((raw.codex===undefined?defaults.codex:raw.codex),50000).map(c=>{if(!CODEX_CATEGORIES.includes(c.category)||!['planned','active','done','saved','archived'].includes(c.status)||!obj(c.details))fail('Некорректная запись Кодекса.');const details={};for(const key of fieldNames)if(c.details[key]!==undefined)details[key]=text(c.details[key],3000);const rating=c.rating===null?null:num(c.rating,10);return {id:id(c.id),title:text(c.title,160),category:c.category,status:c.status,tags:words(c.tags),rating,attitude:text(c.attitude,500),notes:text(c.notes,5000),addedAt:date(c.addedAt),missionId:optional(c.missionId),details}}));
 const prefs=raw.settings.brainProfile??{period:'30',category:'logic'};if(!['7','30','90','all'].includes(prefs.period)||!BRAIN_CATEGORIES.some(c=>c.id===prefs.category))fail('Некорректные настройки профиля способностей.');out.settings.brainProfile={period:prefs.period,category:prefs.category};return out
 }
};

