from pathlib import Path
p=Path('outputs/index.html');s=p.read_text()
extra=Path('work/stats-ranks.js').read_text()
s=s.replace('// ── Achievements and analytics',extra+'\n// ── Achievements and analytics',1)
s=s.replace("title:'В начале пути',onboarded:false","title:'В начале пути',onboarded:false,ranks:structuredClone(DEFAULT_RANKS)",1)
s=s.replace('sidebarCollapsed:false},recentCommands:[]','sidebarCollapsed:false,developmentChart:{...CHART_DEFAULTS,axes:[]}},recentCommands:[]',1)
s=s.replace('${esc(state.profile.title)}</p><div class="profile-foot">','${esc(rankFor())}</p>${state.profile.title&&state.profile.title!==\'В начале пути\'?`<p class="dim" style="font-size:12px">${esc(state.profile.title)}</p>`:\'\'}<div class="profile-foot">',1)
s=s.replace('Уровень ${XPSystem.level(totalXP()).level}</div>','${esc(rankFor())} · Ур. ${XPSystem.level(totalXP()).level}</div>',1)
s=s.replace('Уровень профиля повышен до ${XPSystem.level(totalXP()).level}</p>','${esc(rankFor())} — уровень ${XPSystem.level(totalXP()).level}</p>',1)
s=s.replace("function bindView(){","function bindView(){bindDevelopment();",1)
start=s.index('<div class="cards two"><section class="panel pad"><div class="flex between"><h2>Активность за неделю')
end=s.index('<div class="stats space">',start)
s=s[:start]+'${developmentChart()}<section class="panel pad space"><div class="flex between wrap"><h2>Активность за неделю</h2><span class="pill">Последние 7 дней</span></div>${activityChart()}</section>'+s[end:]
s=s.replace('<label class="field">Титул профиля<input id="profile-title"','<label class="field">Личная подпись<input id="profile-title"',1)
s=s.replace('<p class="field-hint">Уровень и опыт рассчитываются из выполненных миссий и тренировок.</p>', '<div class="rank-banner"><span class="skill-icon" style="--c:var(--gold)">${icon(\'award\',21)}</span><div class="grow"><strong>${esc(rankFor())}</strong><p class="field-hint">Уровень ${XPSystem.level(totalXP()).level} · название меняется с прогрессом</p></div></div><button class="btn" id="edit-ranks">Настроить названия уровней</button><p class="field-hint">Уровень и опыт рассчитываются из выполненных миссий и тренировок.</p>',1)
# Old backups migrate to defaults; new preferences and rank names are validated.
needle='output.recentCommands=arr(raw.recentCommands||[],30)'
validation="""const ranks=raw.profile.ranks===undefined?structuredClone(DEFAULT_RANKS):arr(raw.profile.ranks,30).map(r=>({level:num(r.level,1,10000),name:text(r.name,60).trim()}));ranks.sort((a,b)=>a.level-b.level);if(!ranks.length||ranks[0].level!==1||ranks.some(r=>!Number.isInteger(r.level)||!r.name)||new Set(ranks.map(r=>r.level)).size!==ranks.length)fail('Некорректные названия уровней.');output.profile.ranks=ranks;const cp=s.developmentChart;if(cp!==undefined){if(!obj(cp)||!['radar','bars','cards'].includes(cp.view)||!['xp','sessions','minutes'].includes(cp.metric)||!['attributes','categories'].includes(cp.group)||!['all','week','month'].includes(cp.period))fail('Некорректные настройки статистики.');output.settings.developmentChart={view:cp.view,metric:cp.metric,group:cp.group,period:cp.period,axes:[...new Set(arr(cp.axes,8).map(v=>text(v,100)))]};}else output.settings.developmentChart={...CHART_DEFAULTS,axes:[]};"""
assert needle in s;s=s.replace(needle,validation+needle,1)
# Give cognitive sessions the same profile-level feedback as missions.
s=s.replace('oldLevel=a.level;const record=', 'oldLevel=a.level,oldProfileLevel=XPSystem.level(totalXP()).level;const record=',1)
s=s.replace("recalcAttributes();if(a.level>oldLevel)","recalcAttributes();if(XPSystem.level(totalXP()).level>oldProfileLevel){addActivity(rankFor()+' — уровень '+XPSystem.level(totalXP()).level,'level');toast(rankFor()+' · Уровень '+XPSystem.level(totalXP()).level)}if(a.level>oldLevel)",1)
css='''
.development-panel{margin-top:24px;background:radial-gradient(ellipse at 25% 50%,#28494322,transparent 65%),var(--panel)}.chart-switch{display:flex;gap:4px;padding:4px;border:1px solid var(--line);border-radius:11px}.chart-switch .btn{min-height:35px;padding:7px 11px;font-size:13px}.chart-controls{display:grid;grid-template-columns:1fr 1fr 1fr auto;gap:12px;align-items:end}.development-layout{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(210px,1fr);gap:30px;align-items:center;margin-top:24px}.development-visual{min-width:0}.radar-chart{width:100%;height:auto;display:block;max-height:490px}.radar-label{fill:var(--text);font:13px var(--font)}.radar-value{fill:var(--accent);font:12px var(--font)}.radar-scale{fill:var(--dim);font:10px var(--font)}.legend-row{display:flex;align-items:center;gap:12px;padding:14px 0;border-bottom:1px solid var(--line);font-size:13px}.legend-row strong{white-space:nowrap;font-weight:500}.legend-row small{font-weight:400}.indicator-cards{display:grid;grid-template-columns:1fr 1fr;gap:12px}.indicator-card{padding:17px;border:1px solid var(--line);border-top:2px solid var(--c);background:#0f181955;border-radius:10px}.indicator-card strong{display:block;font-size:26px;font-weight:500;margin:12px 0;color:var(--c)}.indicator-card strong small{font-size:12px}.dev-bar-row{font-size:14px;padding:6px 0}.dev-bar-row strong{font-weight:500}.rank-row{display:grid;grid-template-columns:85px minmax(0,1fr) 32px;align-items:end;gap:12px;margin-bottom:12px}.rank-row .icon-btn{margin-bottom:3px}.rank-banner{display:flex;align-items:center;gap:13px;border:1px solid #625b3a;padding:15px;border-radius:10px;background:#c9af7707}.rank-banner strong{color:var(--gold);font-size:20px;font-weight:500}
@media(max-width:1100px){.development-layout{grid-template-columns:1fr}.development-legend{display:grid;grid-template-columns:1fr 1fr;column-gap:20px}.development-legend>.eyebrow,.development-legend>p{grid-column:1/-1}.radar-chart{max-height:440px}.chart-controls{grid-template-columns:1fr 1fr}}
@media(max-width:767px){.chart-switch{width:100%;justify-content:space-between}.chart-switch .btn{font-size:12px;padding:7px 9px}.development-layout{gap:12px}.development-panel{padding:16px!important}.development-legend{display:block}.chart-controls{gap:10px}.chart-controls label{font-size:12px}.chart-controls select{font-size:12px;padding:10px 7px}.chart-controls .btn{font-size:12px;padding:10px 7px}.radar-chart{min-width:0}.rank-row{grid-template-columns:70px minmax(0,1fr) 28px;gap:8px}.indicator-card{padding:12px}}
'''
s=s.replace('</style>',css+'</style>',1)
p.write_text(s);Path('work/app-script.js').write_text(s.split('<script>')[1].split('</script>')[0])
