const SocialRadar={
 categories:[
  {name:'Работа',roles:['коллега','руководитель проекта','участник команды'],offers:['попробовать новый порядок работы','перенести срок общей задачи','иначе распределить ответственность']},
  {name:'Дружба',roles:['друг','приятель','близкий знакомый'],offers:['вместе организовать встречу','помочь с переездом','изменить совместные планы']},
  {name:'Знакомства и отношения',roles:['новый знакомый','партнёр','человек, с которым вы недавно познакомились'],offers:['чаще встречаться','заранее спланировать выходные','обсудить ожидания от общения']},
  {name:'Переговоры',roles:['заказчик','партнёр по сделке','исполнитель'],offers:['изменить условия соглашения','согласовать новый срок','попробовать небольшой совместный проект']},
  {name:'Групповая динамика',roles:['участник инициативной группы','координатор встречи','организатор команды'],offers:['изменить общий план','распределить роли в группе','обсудить спорное решение']},
  {name:'Распознавание манипуляций',roles:['знакомый','партнёр по договорённости','участник группы'],offers:['принять совместное решение','взять дополнительное обязательство','изменить прежнюю договорённость']}
 ],
 motives:[
  {goal:'избежать лишней нагрузки',fear:'не справиться с дополнительными делами',hint:'В прошлый раз человек просил заранее оценить затраты времени.',reveal:'Мне интересен сам вариант. Но сейчас дополнительные дела не помещаются в мой график.',prediction:'Попросит уменьшить объём участия или перенести срок.',question:'Какая часть участия сейчас потребует слишком много времени?',reply:'Давай ограничим объём и выберем срок, который тебе подходит.'},
  {goal:'снизить риск неудачи',fear:'взять на себя слишком большой риск',hint:'Раньше человек просил сначала проверить новый подход на небольшом примере.',reveal:'Мне важно сначала убедиться, что это сработает. Без небольшой пробы я не готов брать обязательства.',prediction:'Предложит небольшой пробный шаг.',question:'Что помогло бы безопасно проверить этот вариант?',reply:'Начнём с маленькой обратимой пробы и заранее договоримся, как оценим результат.'},
  {goal:'получить недостающие сведения',fear:'решить без понимания условий',hint:'В предыдущем разговоре человек задавал вопросы об условиях, но ответы были неполными.',reveal:'Я пока не понимаю точных условий. Мне нужно знать, что от меня потребуется, прежде чем решать.',prediction:'Запросит конкретные условия.',question:'Какой информации тебе сейчас не хватает для решения?',reply:'Уточню условия, после этого ты сможешь спокойно решить.'},
  {goal:'согласовать решение с другим участником',fear:'нарушить общую договорённость',hint:'Человек уже упоминал, что такие решения обсуждает с другим участником.',reveal:'Я не решаю это в одиночку: у нас есть общая договорённость. Сначала нужно обсудить вариант вместе.',prediction:'Возьмёт паузу для согласования.',question:'С кем ещё нужно согласовать этот вариант и что для них важно?',reply:'Давай оставим время на согласование и вернёмся к разговору после него.'},
  {goal:'добиться более подходящих условий',fear:'согласиться на невыгодные условия',hint:'Ранее человек сравнивал несколько вариантов и спрашивал, что можно изменить.',reveal:'В целом мне это интересно, но текущие условия мне не подходят. Я готов обсудить другой вариант.',prediction:'Предложит изменить условия.',question:'Какие условия сделали бы предложение приемлемым?',reply:'Обсудим, что важно каждой стороне и какие изменения устроят нас обоих.'},
  {goal:'отказаться, сохранив добрые отношения',fear:'обидеть резким отказом',hint:'Человек дважды отклонил предложенные варианты и не предложил встречного.',reveal:'Спасибо за предложение. Я не хочу участвовать и раньше говорил об этом слишком уклончиво.',prediction:'Откажется от участия.',question:'Тебе нужны другие условия или ты предпочитаешь совсем не участвовать?',reply:'Спасибо за прямой ответ. Я уважаю твой отказ.'},
  {goal:'сохранить возможность высказать своё мнение',fear:'потерять голос в общем решении',hint:'В прошлый раз решение объявили до того, как человек успел высказаться.',reveal:'Мне важно, чтобы моё мнение услышали до окончательного решения. Сейчас у меня есть возражение по существу.',prediction:'Попросит обсудить своё возражение.',question:'Какое возражение мы ещё не обсудили?',reply:'Давай сначала выслушаем твоё возражение и проверим, что можно учесть.'}
 ],
 tactics:[
  ['Давление чувством вины','После всего, что я для тебя сделал, ты просто обязан согласиться.','Прошлая помощь используется как основание для обязательного согласия.'],
  ['Искусственная срочность','Решай прямо сейчас. Завтра возможности уже не будет, причину срока я не объясню.','Срок требуют принять без проверяемого обоснования.'],
  ['Ложная дилемма','Либо принимаешь всё без изменений, либо ты против нас.','Разные позиции сведены к двум крайностям.'],
  ['Давление авторитетом','Это одобрил очень важный человек, поэтому вопросы здесь не нужны.','Статус подменяет проверку условий и доводов.'],
  ['Лесть ради уступки','Только такой талантливый человек, как ты, возьмёт всё на себя без обсуждения условий.','Комплимент связан с требованием односторонней уступки.'],
  ['Уход от темы','Не будем про условия. Лучше вспомни, сколько ошибок ты допустил раньше.','Вопрос об условиях заменён обсуждением чужих ошибок.'],
  ['Решение без информации','Подтверди участие сейчас, а детали я расскажу только после согласия.','Необходимые для решения сведения удерживаются до обязательства.'],
  ['Эмоциональное давление','Мне станет ужасно плохо, если ты сейчас не согласишься. Ты этого хочешь?','Ответственность за чужие переживания связывается с обязательным согласием.'],
  ['Навязанное обязательство','Ты выслушал предложение, значит, уже согласился участвовать.','Внимание к предложению ошибочно приравнивается к согласию.']
 ],
 labels:[['accuracy','Точность социальных выводов'],['calibration','Калибровка уверенности'],['motives','Понимание мотивов'],['questions','Уточняющие вопросы'],['updating','Обновление гипотезы'],['prediction','Прогноз поведения'],['manipulation','Распознавание манипуляций'],['negotiation','Переговорные решения']],
 pick(list){return list[rand(0,list.length-1)]},
 question(kind,title,correct,wrong,why,alternative='Другие мотивы возможны: вывод относится к этой учебной ситуации, а не к людям вообще.'){
 const options=shuffle([{text:correct,correct:true},...shuffle([...new Set(wrong)].filter(x=>x!==correct)).slice(0,3).map(text=>({text,correct:false}))]);
 return {kind,title,options:options.map(x=>x.text),answer:options.findIndex(x=>x.correct),why,alternative}
 },
 calibration(confidence,target,correct){return Math.max(0,Math.round(100-Math.abs(confidence-(correct?target:10))*1.25))},
 adapt(level,quality,streak){const direction=quality>=80?1:quality<55?-1:0;const next=direction&&Math.sign(streak)===direction?streak+direction:direction;if(Math.abs(next)>=2)return {level:Math.max(1,Math.min(5,level+direction)),streak:0};return {level,streak:next}},
 generate(level,category,index=0){
 const group=this.categories[category],motiveIndex=rand(0,this.motives.length-1),m=this.motives[motiveIndex],name=this.pick(['Саша','Женя','Валя','Слава','Никита','Даня','Илья','Лёша']),role=this.pick(group.roles),offer=this.pick(group.offers),days=rand(2,12),manip=category===5,tactic=manip?this.pick(this.tactics):null;
 const interest=motiveIndex===5?20:this.pick([60,80]),trust=this.pick([30,60,90]),direct=level===1||level===2&&rand(0,2)===0,scarce=!manip&&level>1&&rand(0,level===5?1:3)===0,secondary=this.pick(['сохранить хорошие отношения','быть услышанным без спора','сохранить право на самостоятельное решение']),emotion=this.pick(['спокойное','усталое','напряжённое']),style=direct?'прямой':'осторожный';
 const model={primaryGoal:manip?'получить согласие без проверки условий':m.goal,secondaryGoal:secondary,fear:manip?'столкнуться с проверкой условий':m.fear,hiddenConcern:manip?'нежелание раскрывать условия':m.goal,knowledge:scarce?'начальная причина пользователю неизвестна':'есть наблюдения о препятствии',missingInformation:m.question,trustLevel:trust,interestLevel:interest,communicationStyle:style,emotionalState:emotion,willingnessToBeDirect:direct?90:40,relationshipToUser:trust===90?'давнее сотрудничество':trust===60?'есть опыт общения':'недавнее знакомство',likelyNextAction:manip?'Повторит просьбу согласиться, не уточняя условия.':m.prediction};
 const relationship=trust===90?'Раньше ваши договорённости неоднократно соблюдались.':trust===60?'Вы уже общались, но совместного опыта пока немного.':'Вы недавно познакомились и ещё не проверяли совместные договорённости.';
 const initial=manip?tactic[1]:scarce?'Мне нужно подумать.':direct?m.reveal:level===3?'В целом всё хорошо, но я пока не готов подтвердить участие.':this.pick(['Мне нужно подумать.','Идея интересная. Но сейчас, наверное, не лучший момент.','Не хочу пока обещать. Давай не торопиться.']);
 let context=`${name} — ${role}. Ты предлагаешь ${offer} в ближайшие ${days} дн. ${relationship} ${scarce?'Причины паузы и прежние решения тебе неизвестны.':manip?'На просьбу уточнить условия вместо конкретики приходит такая реплика.':m.hint}`;
 context+=` В начале разговора человек описывает своё состояние как ${emotion} и говорит: «Для меня важно ${secondary}». Это фон, а не доказательство главного мотива.`;
 if(manip)context=`${name} — ${role}. Вы обсуждаете предложение: «${offer}». Собеседник добивается твоего согласия. Срок обсуждения — ${days} дн. ${relationship} На просьбу уточнить условия вместо конкретики приходит такая реплика.`;
 if(level>=4&&!manip)context+=' Ещё один участник просит быстрее договориться; его пожелание не доказывает мотив собеседника.';
 if(level===3&&!scarce&&!manip)context+=' При этом конкретного согласия ещё нет: общая положительная фраза не равна обязательству.';
 const target=scarce?50:direct||manip?90:70,goal=model.primaryGoal,others=this.motives.filter((_,i)=>i!==motiveIndex),uncertain='Недостаточно информации, чтобы выделить один мотив.';
 const initialCorrect=manip?'В реплике есть давление; скрытый мотив пока нельзя считать доказанным.':scarce?uncertain:`Вероятнее всего, человек хочет ${goal}.`;
 const hypothesis=this.question('motives','Что здесь вероятнее всего происходит?',initialCorrect,manip?['Человек точно желает мне зла.','Нужно согласиться: эта фраза доказывает, что выбора нет.','Никакого воздействия в реплике нет.']:[...others.map(x=>`Вероятнее всего, человек хочет ${x.goal}.`),scarce?`Вероятнее всего, человек хочет ${goal}.`:uncertain],scarce?'Есть только факт паузы. Он совместим с разными мотивами, поэтому сейчас полезнее собрать сведения.':manip?`${tactic[2]} Это наблюдаемая форма воздействия; намерение причинить вред из неё не следует.`:`${level===1?'Прямая реплика':'Предыдущее поведение'} поддерживает гипотезу «${goal}». Она объясняет имеющиеся факты лучше альтернатив.`);
 const steps=[{...hypothesis,pending:true}, {kind:'confidence',title:'Насколько ты уверен в оценке мотива?',options:['50%','70%','90%'],target,why:`В этой задаче ориентир — ${target}%: ${scarce?'данных о мотиве мало':target===90?'есть прямые и согласованные сведения':'есть косвенные сигналы, но остаются альтернативы'}. Это учебная шкала достаточности данных, а не измерение чужих мыслей.`}];
 const profile=index%4===2&&!manip,band=n=>n<40?'Низкая':n<75?'Средняя':'Высокая';
 const addProfile=(model,known,updated=false)=>{
  const fields=[['Чего человек хочет?',model.primaryGoal,this.motives.map(x=>x.goal)],['Чего он избегает?',model.fear,this.motives.map(x=>x.fear)],['Насколько заинтересован?',band(model.interestLevel),['Низкая','Средняя','Высокая']],['Насколько доверяет?',band(model.trustLevel),['Низкая','Средняя','Высокая']],['Какой следующий ход вероятнее?',model.likelyNextAction,this.motives.map(x=>x.prediction)]];
  for(const [field,[title,value,wrong]]of fields.entries()){const observable=known||!scarce&&field<2;steps.push(this.question(updated?'updating':'motives',(updated?'Обнови мини-профиль. ':'Мини-профиль. ')+title,observable?value:'Пока неизвестно.',observable?[...wrong,'Пока неизвестно.']:[value,...wrong],observable?'Опирайся на доступные сведения о препятствии; интерес и доверие оценивай только после прямого уточнения. Оценки относятся к текущему предложению.':'До уточнения нельзя надёжно заполнить эту часть профиля. Не подменяй пробел в данных догадкой.'));}
 };
 if(profile)addProfile(model,false);
 steps.push(this.question('questions','Что лучше спросить, чтобы проверить гипотезу?',manip?'Какие условия и основания решения можно проверить до моего согласия?':scarce?'Что сейчас мешает принять решение и что тебе важно уточнить?':m.question,['Почему ты всегда всё усложняешь?','Ты просто не уважаешь меня, верно?','Я уже знаю твои мотивы. Зачем ты это скрываешь?'],'Открытый вопрос уточняет препятствие и оставляет право ответить свободно. Он не содержит обвинения и не навязывает мотив.'));
 const trustLine=trust===90?'На наши договорённости я могу уверенно опереться.':trust===60?'В целом я тебе доверяю, но важные условия пока хочу проверять.':'Я пока мало тебя знаю и не готов полагаться на обещание без проверки.';
 const interestLine=interest===20?'Участвовать мне неинтересно.':interest===60?'Умеренный интерес есть, но это не приоритет.':'Само предложение меня очень интересует.';
 const reveal=manip?'Я не готов обсуждать детали. Сначала согласись, потом разберёмся.':`${m.reveal} ${interestLine} ${trustLine}`;
 steps.push({...this.question('updating','С учётом новой информации: как ты обновишь вывод?',manip?'Человек продолжает добиваться согласия без проверки условий.':`Сейчас основное препятствие — желание ${goal}.`,manip?['Все условия уже ясны.','Доверие доказано, вопросы больше не нужны.','Нужно согласиться, чтобы успокоить собеседника.']:others.map(x=>`Сейчас основное препятствие — желание ${x.goal}.`),'Новая реплика даёт сведения о препятствии. Обновляй гипотезу по содержанию ответа, даже если первая догадка была другой.'),reveal});
 if(profile)addProfile(model,true,true);
 steps.push(this.question('prediction','Какой следующий ход наиболее вероятен, если условия не изменятся?',model.likelyNextAction,[...others.map(x=>x.prediction),'Немедленно согласится без обсуждения.'],'Прогноз следует из обозначенного препятствия и предыдущего ответа. Это вероятный ход в модели, а не гарантия поведения реального человека.'));
 if(manip)steps.push(this.question('manipulation','Какой приём воздействия заметен в исходной реплике?',tactic[0],this.tactics.map(t=>t[0]),tactic[2],'Наличие давления не доказывает намерение навредить. Можно обозначить границы и запросить проверяемые условия.'));
 if(manip||index%2===1)steps.push(this.question('negotiation','Как лучше ответить?',manip?'Я не буду принимать обязательство без понятных условий. Вернёмся к разговору, когда они будут доступны.':m.reply,['Согласись немедленно, иначе пожалеешь.','Хорошо, решу за тебя и сообщу остальным.','Ты должен согласиться, ведь я столько для тебя сделал.'],'Эта реплика учитывает интересы обеих сторон, снижает неопределённость и сохраняет право отказаться.'));
 let changedModel=null;
 if(level===5&&!manip){const changedIndex=this.pick(this.motives.map((_,i)=>i).filter(i=>i!==motiveIndex&&i!==5)),changed=this.motives[changedIndex];changedModel={...model,primaryGoal:changed.goal,fear:changed.fear,likelyNextAction:changed.prediction,interestLevel:80,trustLevel:60};steps.push({...this.question('updating','После изменения обстоятельств: какая гипотеза теперь лучше?',`Теперь человек хочет ${changed.goal}.`,[`Главным остаётся желание ${m.goal}.`,...this.motives.filter((_,i)=>i!==changedIndex&&i!==motiveIndex).map(x=>`Теперь человек хочет ${x.goal}.`)],'Предыдущее препятствие снято, но появилось новое. Сохранять первую гипотезу вопреки новым сведениям не стоит.'),reveal:`Позже ${name} уточняет: «Прежнее препятствие больше не актуально. Появились новые обстоятельства: ${changed.reveal} Сам вариант теперь очень интересен; я в целом доверяю тебе, но хочу проверить условия».`});if(profile)addProfile(changedModel,true,true);steps.push(this.question('prediction','Что теперь вероятнее всего произойдёт?',changed.prediction,this.motives.filter((_,i)=>i!==changedIndex).map(x=>x.prediction),'Прогноз нужно пересчитать после изменения препятствия.'))}
 return {key:[category,motiveIndex,name,role,offer,days,interest,trust,style,secondary,emotion,scarce,tactic?.[0]].join('|'),category:group.name,context,initial,model,changedModel,steps,level,mode:manip?'Распознавание давления':profile?'Модель человека':index%2?'Диалог и переговоры':'Анализ и прогноз'};
 },
 summary(metrics){return `<div class="game-metrics wide" style="grid-template-columns:repeat(auto-fit,minmax(125px,1fr))">${this.labels.map(([key,label])=>`<div><strong>${metrics[key]??0}%</strong>${label}</div>`).join('')}</div>`},
 intro(){const past=brainRecords('social'),last=past.at(-1),level=last?.metrics.nextLevel||1;$('#game-body').innerHTML=`<div class="game-panel"><h3 class="game-title">Социальный радар</h3><p class="muted">Учись понимать мотивы людей, замечать скрытые интересы, проверять свои гипотезы и прогнозировать поведение.</p><p class="small muted">8 новых ситуаций: наблюдение → гипотеза → уверенность → вопрос → новые сведения → пересмотр → прогноз. Иногда данных недостаточно — это полноценный ответ.</p><p class="field-hint">Уверенность относится к оценке мотива. Учебные ориентиры: 50% при нехватке данных, 70% при косвенных сигналах, 90% при прямых согласованных сведениях. Это не вероятности чувств реальных людей. Скорость не добавляет баллы.</p><button class="btn primary" id="social-start">Начать · уровень ${level}/5</button>${last?`<details class="wide space"><summary>Последний результат · ${last.score}/100</summary>${this.summary(last.metrics)}</details>`:''}<p class="field-hint">Повторы без лимита. Незавершённая сессия не начисляет опыт.</p></div>`;$('#social-start').onclick=()=>this.start()},
 start(){const session=BrainLab.session;if(!session)return;session.start=performance.now();const active=()=>BrainLab.session===session&&!session.saved;let level=brainRecords('social').at(-1)?.metrics.nextLevel||1,peak=level,streak=0,index=0;const totals={},seen=new Set(),categories=shuffle([0,1,2,3,4,5,...shuffle([0,1,2,3,4,5]).slice(0,2)]);let currentTotals;
 const add=(key,value)=>{for(const target of [totals,currentTotals]){target[key]??=[];target[key].push(value)}};
 const percent=(source,key)=>source[key]?.length?Math.round(source[key].reduce((a,b)=>a+b,0)/source[key].length):0;
 const metricsFrom=source=>{const metrics=Object.fromEntries(this.labels.map(([key])=>[key,percent(source,key)])),conclusions=['motives','updating','prediction'].flatMap(k=>source[k]||[]);metrics.accuracy=conclusions.length?Math.round(conclusions.reduce((a,b)=>a+b,0)/conclusions.length):0;return metrics};
 const quality=source=>{const parts=[['motives',25],['calibration',20],['questions',15],['updating',20],['prediction',10],['manipulation',5],['negotiation',5]].filter(([k])=>source[k]?.length);return Math.round(parts.reduce((n,[k,w])=>n+percent(source,k)*w,0)/parts.reduce((n,[,w])=>n+w,0))};
 const scenario=()=>{if(!active())return;let task;for(let attempt=0;attempt<30;attempt++){task=this.generate(level,categories[index],index);if(!seen.has(task.key))break}seen.add(task.key);currentTotals={};let stepIndex=0,pending=null,questionOK=true,transcript=[],version=0;
 const show=()=>{if(!active())return;const step=task.steps[stepIndex],ticket=++version;let answered=false;if(step.reveal){transcript.push({text:step.reveal,repair:!questionOK&&stepIndex<task.steps.length-2});questionOK=true}
 $('#game-body').innerHTML=`<div class="flex between wrap"><button class="btn small" id="social-back">← Назад</button><span class="small muted">Социальный радар · ${index+1} / 8 · Уровень ${level}/5</span></div><p class="case-label space">${esc(task.category)} · ${esc(task.mode)}</p>${stepIndex?'<details class="space"><summary>Контекст и исходная реплика</summary>':''}<p class="muted space">${esc(task.context)}</p><div class="explanation space"><strong>${esc(task.initial)}</strong></div>${stepIndex?'</details>':''}${transcript.map(t=>`<div class="explanation space">${t.repair?'<p class="gold small">На резкий вопрос собеседник не уточнил причину. Для продолжения разбора пробуем нейтральный вопрос: «Что важно прояснить перед решением?»</p>':''}<p><strong>Новая информация:</strong> ${esc(t.text)}</p></div>`).join('')}<h3 class="space" id="social-question" tabindex="-1">${esc(step.title)}</h3><div class="answer-list space">${step.options.map((o,i)=>`<button class="answer" data-social-choice="${i}">${esc(o)}</button>`).join('')}</div><div id="social-feedback" class="space" aria-live="polite"></div>`;
 $('#social-back').onclick=()=>{BrainLab.stop();Modal.close()};$('#social-question').focus({preventScroll:true});$('#game-body').scrollIntoView({block:'start'});
 $$('[data-social-choice]').forEach(b=>b.onclick=()=>{if(answered||!active()||ticket!==version)return;answered=true;const chosen=+b.dataset.socialChoice;
 if(step.pending){pending={ok:chosen===step.answer,step,chosen};stepIndex++;show();return}
 $$('[data-social-choice]').forEach(x=>x.disabled=true);let ok,why=step.why,alternative=step.alternative||'Уверенность должна меняться вместе с качеством доступных сведений.';
 if(step.kind==='confidence'){const value=Number(step.options[chosen].replace('%','')),calibration=this.calibration(value,step.target,pending.ok);add('motives',pending.ok?100:0);add('calibration',calibration);ok=pending.ok;why=`${pending.step.why} Верная оценка: «${pending.step.options[pending.step.answer]}». ${why} Калибровка этого ответа: ${calibration}%.`;alternative=pending.step.alternative}
 else {ok=chosen===step.answer;add(step.kind,ok?100:0);$$('[data-social-choice]').forEach(x=>{if(+x.dataset.socialChoice===step.answer)x.classList.add('correct')});if(step.kind==='questions')questionOK=ok}
 if(!ok)b.classList.add('wrong');$('#social-feedback').innerHTML=`<div class="explanation"><strong>${ok?'Верно. Почему?':'Почему другой ответ точнее?'}</strong><p class="space">${esc(why)}</p><p class="small muted space">Альтернатива: ${esc(alternative)}</p></div><button class="btn primary space" id="social-next">${stepIndex===task.steps.length-1?(index===7?'Посмотреть результат':'Следующая ситуация'):'Продолжить'}</button>`;
 $('#social-feedback').scrollIntoView({block:'nearest'});let advanced=false;$('#social-next').onclick=()=>{if(advanced||!active()||ticket!==version)return;advanced=true;stepIndex++;if(stepIndex<task.steps.length)return show();const adjusted=this.adapt(level,Math.min(quality(currentTotals),percent(currentTotals,'calibration')<75?79:100),streak);level=adjusted.level;streak=adjusted.streak;peak=Math.max(peak,level);index++;if(index<8)return scenario();const metrics={...metricsFrom(totals),level:peak,nextLevel:level,rounds:8,averageTime:Math.round((performance.now()-session.start)/8)},score=quality(totals);BrainLab.result('Социальный радар — сессия завершена',`<p class="accent" style="font-size:28px">${score}/100 баллов</p><p class="muted">Достигнутый уровень: ${peak}/5 · Следующая сессия: ${level}/5</p>${this.summary(metrics)}<p class="field-hint">Баллы учитывают выводы, уверенность, вопросы и обновление модели. Скорость не влияет на награду. Показатели описывают решение учебных ситуаций.</p>`,'social',metrics,score,metrics.accuracy>0)}})
 };show()};scenario()
 }
};

